---
title: "Assignments"
---

There will be three types of assignments in this course: weekly summaries, three papers, and one oral presentation.

## Weekly Summaries (15% of final grade)

Each week for 9 weeks, you will summarize one of the readings (the one bolded in the syllabus). That means you can skip some weeks. It is up to you which weeks you decide to skip. The summary must be no longer than three-quarters of a page (single-spaced, 12-point font). These summaries must be submitted via Canvas by **10:50 am** on Thursdays. No credit will be given for submissions after class has started.

You can find a brief guide on how to write a summary [here](../resource/summaries.html).


## Three Papers 

For this course, you will write three papers in addition to smaller assignments throughout the semester to help you develop your ideas and receive feedback on/for these pieces.

**1. Literature Review (15% of final grade):** You will select a topic of interest to you (in Latina/o politics) and write a review of the literature in said topic. Ideally, you will pick a topic that you will explore further in your final paper (see below).

**2. Campaign memo (15% of final grade):** You will write a campaign memo on the political attitudes and behaviors of Latinos/as. Your audience for this memo will be a hypothetical campaign for Senate where you are working.

**3. Final paper (20% of final grade):** In your final paper, you will write the "front end of a research paper." This means you will have a research question, literature review, expectations based on theory, and a research design. Ideally, the question will be the same as the one that motivated the literature review from earlier in the course (but it may also be a different one).


We will work on different parts of the final paper over the course of the semester.

- Topic proposal with research question (due date TBD)
- Literature review (due date TBD)
- Research design (due date TBD)


## Oral Presentation (15% of final grade)

You will do a conference-style presentation of your final paper.

I will provide further instructions later on.



