project:
  type: website
  render:
    - "*.qmd"

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "POLI 328: Latina/o Politics in the US"
  site-url: "https://equezadallanes.github.io/poli328-spring23/"
  
  navbar:
    pinned: true
    background: "#00205B"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Resources"
        file: resource/index.qmd

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
            
    - title: "Content"
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Topics"
          contents:
            - content/01-intro.qmd
            - content/02-latino-identity.qmd
            - content/03-politicized-identities.qmd
    
    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resource/index.qmd
            - resource/reading.qmd
            - resource/writing.qmd
            - resource/citations.qmd
            - resource/website.qmd


format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai

