project:
  type: website
  render:
    - "*.qmd"

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "POLI 328: Latina/o Politics in the US"
  site-url: "https://poli328.spring23.equezadallanes.com/"
  
  navbar:
    pinned: true
    background: "#00205B"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Resources"
        file: resource/index.qmd

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Assignments"
          contents:
            - assignment/campaign-memo.qmd
            - assignment/literature-list.qmd
            - assignment/literature-review.qmd
            - assignment/oral-presentation.qmd
        - section: "Research Design Paper"
          contents: 
            - assignment/final-paper.qmd
            - assignment/research-question.qmd
            - assignment/literature-list.qmd
            - assignment/literature-review.qmd
            - assignment/research-design.qmd
            
    - title: "Content"
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Topics"
          contents:
            - content/01-intro.qmd
            - content/02-latino-identity.qmd
            - content/03-politicized-identities.qmd
            - content/04-history-demographics.qmd
            - content/05-behavior.qmd
            - content/06-partisanship-ideology.qmd
            - content/07-latino-activism.qmd
            - content/08-participation.qmd
            - content/09-religion.qmd
            - content/10-immigration.qmd
            - content/11-representation.qmd
            - content/12-elections.qmd
            - content/13-perceptions.qmd
    
    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resource/index.qmd
            - resource/reading.qmd
            - resource/writing.qmd
            - resource/summaries.qmd
            - resource/citations.qmd
            - resource/journals.qmd
            - resource/website.qmd


format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai

