---
title: "Latina/o/x Identity"
---

## Tuesday, January 17

### Readings 

1. Sanchez, Gabriel R., and Natalie Masuoka. 2010. ["Brown-Utility Heuristic? The Presence and Contributing Factors of Latino Linked Fate."](https://doi.org/10.1177/0739986310383129) *Hispanic Journal of Behavioral Sciences* 32(4): 519–31. ({{< fa file-pdf >}} available on Canvas)

2. Noe-Bustamante, Luis, Lauren Mora, and Mark Hugo Lopez. 2020. ``About One-in-Four U.S. Hispanics Have Heard of Latinx, but Just 3\% Use It.'' *Pew Research Center.* [{{< fa arrow-up-right-from-square >}}](https://www.pewresearch.org/hispanic/2020/08/11/about-one-in-four-u-s-hispanics-have-heard-of-latinx-but-just-3-use-it/)


### For class

- [Arkansas governemnt banned the term Latinx from official documents.](https://nypost.com/2023/01/11/gov-sarah-huckabee-sanders-bans-latinx-from-arkansas-govt-docs/)


---

## Thursday, January 19

### Readings

1. **Zepeda-Millán, Chris, and Sophia J. Wallace. 2013. ["Racialization in Times of Contention: How Social Movements Influence Latino Racial Identity."](https://doi.org/10.1080/21565503.2013.842492) *Politics, Groups, and Identities* 1(4): 510–27.** ({{< fa file-pdf >}} available on Canvas)
 

---
 
## Discussion Questions (submitted by students)

1. Do Hispanics use the term Latinx or is it mainly just by and for white activists?
2. Do Hispanic immigrants behave differently than US-born Hispanics? How?
3. What are differences in political ideologies between Latinos that immigrated to the US vs those born in the US?
4. Do Latine people actually care about the Latino/a/e discourse or is it a more superficial political topic? Should it be more relevant?
5. Why has the number of Hispanics identifying as white declined from 2010 to 2021, despite the Hispanic population increasing?
