---
title: "Latino Partisanship, Ideology, and Public Opinion"
---

## Tuesday, February 14

### Readings 

1. de la Garza, Rodolfo O., and Jeronimo Cortina. 2007. ["Are Latinos Republicans But Just Don’t Know It?: The Latino Vote in the 2000 and 2004 Presidential Elections."](https://doi.org/10.1177/1532673X06294885) *American Politics Research* 35(2): 202–23. ({{< fa file-pdf >}} available on Canvas)

2. Gonzalez Juenke, Eric. 2016. ["Viable Republicans or Fool’s Gold? The Consequences of Confusing Latino Respondents with Latino Voters."](https://doi.org/10.1080/21565503.2015.1050419) *Politics, Groups, and Identities* 4(4): 598–617. ({{< fa file-pdf >}} available on Canvas)


---


## Thursday, February 16

### Readings 

1. **Bejarano, Christina E. 2014. ["Latino Gender and Generation Gaps in Political Ideology."](https://doi.org/10.1017/S1743923X13000548) *Politics & Gender* 10(1): 62–88.** ({{< fa file-pdf >}} available on Canvas)

2. Michelson, Melissa R. 2016. ["Healthy Skepticism or Corrosive Cynicism? New Insights into the Roots and Results of Latino Political Cynicism."](https://doi.org/10.7758/RSF.2016.2.3.04) *RSF: The Russell Sage Foundation Journal of the Social Sciences* 2(3): 60–77. ({{< fa file-pdf >}} available on Canvas)


 
