---
title: "Contemporary Trends and Determinants of Political Participation"
---

## Tuesday, February 28

### Readings 

1. Barreto, Matt A. 2010. *Ethnic Cues: The Role of Shared Ethnicity in Latino Political Participation.* Ann Arbor: University of Michigan Press. (Chapter 1: "Assessing the Role of Shared Ethnicity in Latino Political Behavior." {{< fa file-pdf >}} available on Canvas)

2. Gutierrez, Angela, Angela X. Ocampo, Matt A. Barreto, and Gary Segura. 2019. ["Somos Más: How Racial Threat and Anger Mobilized Latino Voters in the Trump Era."](https://doi.org/10.1177/1065912919844327) *Political Research Quarterly* 72(4): 960–75. ({{< fa file-pdf >}} available on Canvas)


### For class

- [Pew report](https://www.pewresearch.org/fact-tank/2022/10/12/key-facts-about-hispanic-eligible-voters-in-2022/)


---


## Thursday, March 2

### Readings 

1. Gershon, Sarah Allen, Adrian D. Pantoja, and J. Benjamin Taylor. 2016. ["God in the Barrio?: The Determinants of Religiosity and Civic Engagement among Latinos in the United States."](https://doi.org/10.1017/S175504831600002X) *Politics and Religion* 9(1): 84–110. ({{< fa file-pdf >}} available on Canvas)

2. **Marschall, Melissa J., and Amanda Rutherford. 2016. ["Voting Rights for Whom? Examining the Effects of the Voting Rights Act on Latino Political Incorporation."](https://doi.org/10.1111/ajps.12182) *American Journal of Political Science* 60(3): 590–606.** ({{< fa file-pdf >}} available on Canvas)


 
