---
title: "Representation"
---

## Tuesday, March 28

### Readings 

1. **Preuhs, Robert R. 2007. ["Descriptive Representation as a Mechanism to Mitigate Policy Backlash: Latino Incorporation and Welfare Policy in the American States."](https://doi.org/10.1177/1065912907301981) *Political Research Quarterly* 60(2): 277–92.** ({{< fa file-pdf >}} available on Canvas)

---


## Thursday, March 30

### Readings 

1. Casellas, Jason P. 2009. ["The Institutional and Demographic Determinants of Latino Representation."](https://doi.org/10.3162/036298009788897781) *Legislative Studies Quarterly* 34(3): 399–426. ({{< fa file-pdf >}} available on Canvas)

2. Gonzalez Juenke, Eric. 2014. ["Ignorance Is Bias: The Effect of Latino Losers on Models of Latino Representation."](https://doi.org/10.1111/ajps.12092) *American Journal of Political Science* 58(3): 593–603. ({{< fa file-pdf >}} available on Canvas)


### For class

* [2021 National Directory of Latino Elected Officials](https://naleo.org/wp-content/uploads/2022/01/2021-National-Directory-Latino-Elected-Officials.pdf)

* [Demographics and Redistricting in Texas after the 2020 Census](https://www.texastribune.org/2021/12/08/texas-redistricting-demographics-elections/)

* [Demographics of Texas Congressional Districts](https://statisticalatlas.com/congressional-district/Texas/Congressional-District-20/Race-and-Ethnicity#figure/congressional-district-in-texas/hispanic)

* [Demographics of Congressional Districts (All States) by the U.S. Census Bureau](https://www.census.gov/mycd/?st=48&cd=34)



 
